// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NotificationCheckerController from "./notification_checker_controller"
application.register("notification-checker", NotificationCheckerController)

import NotificationTypeController from "./notification_type_controller"
application.register("notification-type", NotificationTypeController)
